version: "3"

services:

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack-python-async-sqs-consumer}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./volumes/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
